- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml
  pre_tasks:
    - name: update repo index
      apt: update_cache=yes state=latest
      changed_when: False
      ignore_errors: yes

  tasks:
    - include: tasks/packages.yml
    - include: tasks/docker.yml
