- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml
  pre_tasks:
    - name: Update repo index
      apt: update_cache=yes state=latest
      changed_when: False
      ignore_errors: yes
    - name: Create /etc/scripts directory if it doesn't exist
      file: path=/etc/scripts state=directory
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/docker.yml
    - include: tasks/node.yml
    - include: tasks/ethereum.yml
    - include: tasks/npm_pacakges.yml
    - include: tasks/gcloud.yml
