- name: Download nvm install script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
    dest: /etc/scripts/nvm-install.sh
    mode: 'u+x,g+x,o+x'

- name: Install nvm
  become: yes
  become_user: tom 
  command: /etc/scripts/nvm-install.sh

- name: Install Node LTS 
  become: yes
  become_user: tom 
  shell: source /home/tom/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash

- name: Create .yvm dir
  become: yes
  become_user: tom
  file: path=/home/tom/.yvm state=directory
  changed_when: False

- name: Download yvm install script
  get_url: 
    url: https://github.com/tophat/yvm/releases/download/v3.6.7/yvm.js 
    dest: /home/tom/.yvm
    mode: 'u+x,g+x,o+x'

- name: Install yvm
  become: yes
  become_user: tom
  command: /home/tom/.nvm/versions/node/v12.16.3/bin/node /home/tom/.yvm/yvm.js configure-shell
